### ISSUE TITLE
此demo克隆并使用pnpm安装依赖后运行vuepress报错

### ISSUE THREAD

**Issue by Barry-Flynn** [xinlei3166/vuepress-demo#2]
本Demo克隆到本地后，使用pnpm安装了依赖，然后运行`yarn docs:dev`命令报错如下：

```sh
$ yarn docs:dev
yarn run v1.22.19
$ vuepress dev docs
X [ERROR] Could not resolve "../../dist/node/index.mjs"

    docs/.vuepress/config.js:2:32:
      2 │ import { demoblockPlugin } from '../../dist/node/index.mjs'
        ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: Build failed with 1 error:
docs/.vuepress/config.js:2:32: ERROR: Could not resolve "../../dist/node/index.mjs"
    at failureErrorWithLog (E:\BarryFlynn\vuepress-plugin-demoblock-plus\node_modules\.pnpm\esbuild@0.15.13\node_modules\esbuild\lib\main.js:1566:15)
    at E:\BarryFlynn\vuepress-plugin-demoblock-plus\node_modules\.pnpm\esbuild@0.15.13\node_modules\esbuild\lib\main.js:1024:28
    at runOnEndCallbacks (E:\BarryFlynn\vuepress-plugin-demoblock-plus\node_modules\.pnpm\esbuild@0.15.13\node_modules\esbuild\lib\main.js:1438:61)
    at buildResponseToResult (E:\BarryFlynn\vuepress-plugin-demoblock-plus\node_modules\.pnpm\esbuild@0.15.13\node_modules\esbuild\lib\main.js:1022:7)
    at E:\BarryFlynn\vuepress-plugin-demoblock-plus\node_modules\.pnpm\esbuild@0.15.13\node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (E:\BarryFlynn\vuepress-plugin-demoblock-plus\node_modules\.pnpm\esbuild@0.15.13\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (E:\BarryFlynn\vuepress-plugin-demoblock-plus\node_modules\.pnpm\esbuild@0.15.13\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (E:\BarryFlynn\vuepress-plugin-demoblock-plus\node_modules\.pnpm\esbuild@0.15.13\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

此外，那个`vuepress-plugin-demoblock-plus`插件在我另一个项目里貌似也无法正常使用，即使我将VuePress 版本降为vuepress@2.0.0-beta.51，只要安装那个插件控制台就报错`Uncaught ReferenceError: Cannot access 'clientConfigs' before initialization`，卸载就恢复正常

**Comment by Barry-Flynn** [comment]
是否可能与版本警告有关
```sh
warning "vuepress > vuepress-vite@2.0.0-beta.51" has unmet peer dependency "@vuepress/client@^2.0.0-beta.50".
warning "vuepress > vuepress-vite@2.0.0-beta.51" has unmet peer dependency "vue@^3.2.37".
```
